### ISSUE TITLE
How to install it missing

### ISSUE THREAD

**Issue by Carlopasquinucci** [Unofficial-Extend-Project-Mirror/openfoam-extend-Breeder-other-scripting-PyFoam#1]
Thanks a lot for the nice job, but can you implement the README file with some explanation how to install it?

Thanks!

**Comment by wyldckat** [comment]
1. https://openfoamwiki.net/index.php/Contrib/PyFoam#Installation
2. Official issue tracker for PyFoam: https://openfoamwiki.net/index.php/Contrib/PyFoam#Bug_reporting

**Comment by wyldckat** [comment]
I've updated in the About description of this unofficial repository, where to find this wiki. Please report your request to the official bug tracker for PyFoam.
